#!/bin/bash

# Get IPs
export IP_S11=$(ip addr show $IFACE_S11 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
export IP_S1U=$(ip addr show $IFACE_S1U | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)

# Create confog file from template
envsubst < /home/config/spgw.conf > /usr/local/etc/oai/spgw.conf

# Run S/P GW service
/home/openair-cn/scripts/run_spgw
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start spgw: $status"
  exit $status
fi

