#!/bin/bash

# Wait for HSS
sleep 7

# Get HSS and SPGW IPs
export HSS_IP=$(host $HSS_HOST | egrep -o "has address [0-9]+.+" | cut -d " " -f3)
export SPGW_IP=$(host $SPGW_HOST | egrep -o "has address [0-9]+.+" | cut -d " " -f3)
export IP_S11=$(ip addr show $IFACE_S11 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
export IP_S1=$(ip addr show $IFACE_S1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)

# Create config files based on template
envsubst < /home/config/mme.conf > /usr/local/etc/oai/mme.conf
envsubst < /home/config/mme_fd.conf > /usr/local/etc/oai/freeDiameter/mme_fd.conf

# Chceck MME certificate for Diameter S6a connection
/home/openair-cn/scripts/check_mme_s6a_certificate /usr/local/etc/oai/freeDiameter $MME_HOST.$MME_REALM

# Run MME service
/home/openair-cn/scripts/run_mme
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start mme: $status"
  exit $status
fi
