#!/bin/bash

# Needed becouse of permissions conflict
chown -R mysql:mysql /var/lib/mysql /var/run/mysqld

# Create configs based on template
envsubst < /home/config/hss.conf > /usr/local/etc/oai/hss.conf
envsubst < /home/config/hss_fd.conf > /usr/local/etc/oai/freeDiameter/hss_fd.conf
/home/openair-cn/scripts/check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter $HSS_HOST.$HSS_REALM

# Start database service
# If started import HSS database
service mysql start
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start mysql: $status"
  exit $status
else
  mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "create database oai_db;use oai_db;source /home/db/oai_db.sql;"
fi

# Start Apache for phpmyadmin access
service apache2 start
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start apache2: $status"
  exit $status
fi

# Run HSS service
/home/openair-cn/scripts/run_hss
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start hss: $status"
  exit $status
fi
