#!/bin/bash

# Wait for mysql
sleep 5

# Find mysql IP
export MYSQL_HOST=$(host $MYSQL_HOST | egrep -o "has address [0-9]+.+" | cut -d " " -f3)

# Create configs based on template
envsubst < /home/config/hss.conf > /usr/local/etc/oai/hss.conf
envsubst < /home/config/hss_fd.conf > /usr/local/etc/oai/freeDiameter/hss_fd.conf
/home/openair-cn/scripts/check_hss_s6a_certificate /usr/local/etc/oai/freeDiameter $HSS_HOST.$HSS_REALM

# Run HSS service
/home/openair-cn/scripts/run_hss
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start hss: $status"
  exit $status
fi
